### ISSUE TITLE
Tabbing to next cell in the List Attributes view does not work correctly

### ISSUE THREAD

**Issue by RafalWilinski** [Dynobase/dynobase#120]

**Comment by danbdo** [comment]
Not sure if that is what I just saw. But anyway:
- Add a new partition that has a PK so that it is sorted in front of any of the existing partitions
- Tab out of the PK field after entering it
>> The new partition gets sorted to the top
>> The newly selected attribute is the SK of another partition/type and the existing SK value is killed and replaces by ~new~
