### ISSUE TITLE
In SQL mode, triggered queries often just stay running indefinitely

### ISSUE THREAD

**Issue by lesiki** [Dynobase/dynobase#13]
![Screenshot 2021-07-28 at 15 58 50](https://user-images.githubusercontent.com/1673588/127326133-414d52e2-4069-4ad6-bf23-7607b537e704.png)

The query just stays in "executing" sometimes. I've left it for 10+ minutes in this state without it timing out. Note that this is a table with no more than 2-3k rows.

I'm not sure if this is a dynobase issue or something with DynamoDB's partiql API, but I don't know how to investigate it further. I can't see any pattern to it either, sometimes virtually identical query will execute immediately, and then hang in this endless loading state when I tweak a single value in the query.

**Comment by RafalWilinski** [comment]
Thanks for the bug report! I'll work on providing some better feedback whether query is actually doing something or if it's stuck.
