### ISSUE TITLE
Support hiding in macOS

### ISSUE THREAD

**Issue by chris-erickson** [Dynobase/dynobase#131]
Supporting <kbd>⌘</kbd> + <kbd>H</kbd> to hide the app would be a nice usability improvement on the Mac.

**Comment by chris-erickson** [comment]
@RafalWilinski When you hide the app with Command-H it just closes the Dynobase window and there's no way to get it back besides quitting the app and restarting it.

**Comment by ktwbc** [comment]
Why was this closed? This is still an issue, it's a basic Mac keyboard function that should be supported if you're making a mac app
