### ISSUE TITLE
Adding a field into the designer and then clicking away causes blank screen

### ISSUE THREAD

**Issue by leenattress** [Dynobase/dynobase#136]
**Scenario 1:**
I am in the designer
I click the plus here to add a field
I click away instead of filling it in
The screen goes white
The error shows in the dev tools

![image](https://user-images.githubusercontent.com/127187/143143277-0171d934-773d-4e90-b41e-3cfbe7664599.png)
![image](https://user-images.githubusercontent.com/127187/143143306-25ce1ec8-6711-43bf-bdf4-75a9e8beb9b7.png)
![image](https://user-images.githubusercontent.com/127187/143143066-b8f2988f-f49c-49fa-8d5a-65da5de132fe.png)

---

**Scenario 2:**
I am in the designer
I load an example JSON
I click this plus to add a field
A popup asks me about the change
I ignore it and switch to table view
I get a WSOD and a console error

![image](https://user-images.githubusercontent.com/127187/143143543-64856509-392f-4791-88fa-4a3403b9a951.png)
![image](https://user-images.githubusercontent.com/127187/143143594-c776b781-b7c0-435a-96ed-49f0091520e5.png)
![image](https://user-images.githubusercontent.com/127187/143143661-211534d7-f7dc-43af-9b9d-a2ff27f48d31.png)
![image](https://user-images.githubusercontent.com/127187/143143700-a71896ba-1efa-46ff-821e-8b2ca62e62ba.png)

**Comment by RafalWilinski** [comment]
Thanks for reporting this problem! I'll fix it in the upcoming release.
