### ISSUE TITLE
Single-table designer overwrites existing sort key value when adding new partition key

### ISSUE THREAD

**Issue by savagedev** [Dynobase/dynobase#137]
This is a trivial example to reproduce the issue I'm seeing in version 1.7.6.

In the single-table designer, I have a pk/sk composite key and add a first record pk = z, sk = z. Then I add a new partition key which creates a new, empty record at the bottom of the grid. I add pk = a which immediately does an automatic sort to place the new record at the top of the grid but the edit focus is now in the sk field of the existing pk = z record which has been sorted to the last record in the grid. The sk field on the existing pk = z record is overwritten with the "\~new\~" value.

![image](https://user-images.githubusercontent.com/18244818/143473751-2b866b82-8ccd-42bc-a287-ffd2d772b58a.png)

**Comment by danbdo** [comment]
Yup, I can repro that as well

**Comment by RafalWilinski** [comment]
Fixed in 10.0.0
