### ISSUE TITLE
Copy the UID of the Machine with a click

### ISSUE THREAD

**Issue by alambertt** [Dynobase/dynobase#14]
When I click over the UID should copy the value to the clipboard. I´m using
```
Version: 1.4.5
OS: Windows_NT x64 10.0.19041
```

![image](https://user-images.githubusercontent.com/6148597/127469690-68ee5f4a-de5c-460e-a000-6a1fff14686f.png)

**Comment by RafalWilinski** [comment]
Added!

**Comment by alambertt** [comment]
Excelent 👌🏻Enviado desde mi Galaxy
-------- Mensaje original --------De: Rafal Wilinski ***@***.***> Fecha: 29/8/21  15:55  (GMT-05:00) Para: Dynobase/dynobase ***@***.***> Cc: Angel Lambertt Pierra ***@***.***>, Author ***@***.***> Asunto: Re: [Dynobase/dynobase] Copy the UID of the Machine with a click (#14) 
Added!
