### ISSUE TITLE
regression: Terminal is not having AWS-SDK anymore in the scope

### ISSUE THREAD

**Issue by RafalWilinski** [Dynobase/dynobase#148]

**Comment by RafalWilinski** [comment]
Closed in 1.8.0

**Comment by jonking-ajar** [comment]
I am still seeing this in 1.8.0.

<img width="183" alt="Screen Shot 2022-01-12 at 1 05 48 PM" src="https://user-images.githubusercontent.com/48849815/149213736-ecb86e2d-5eb1-4f6b-a8cb-0433d137b822.png">

<img width="1472" alt="Screen Shot 2022-01-12 at 1 07 13 PM" src="https://user-images.githubusercontent.com/48849815/149213867-502b87c2-70da-4181-86f1-1bb1e8eb8c92.png">
