### ISSUE TITLE
Dynobase -> Check Updates has no effect

### ISSUE THREAD

**Issue by rcoundon** [Dynobase/dynobase#153]
Clicking Check Updates appears to have no effect on: 

Mac OS Big Sur 11.6.2 
Dynobase 1.7.8

Nothing is shown in devtools either.

**Comment by Rukenshia** [comment]
Not sure if related at all, but I also noticed this and when I go to [the changelog](https://dynobase.dev/changelog/) all updates are dated to 2021-10-27.

**Comment by chris-erickson** [comment]
It's been months for me since updates have reliably worked, on only one of my machines. Both are latest of everything, Mac.

**Comment by rcoundon** [comment]
Just experimented using dev tools. There are no console outputs and perhaps more tellingly, no network activity when the Check for Updates button is clicked

**Comment by alambertt** [comment]
Look like #64

**Comment by RafalWilinski** [comment]
Option to manually check for updates has been removed.

**Comment by alambertt** [comment]
> Option to manually check for updates has been removed.

And now? How do we update the client?
