### ISSUE TITLE
Import dynamodb-onetable models is not working

### ISSUE THREAD

**Issue by ebisbe** [Dynobase/dynobase#159]
Load one of the samples. Save it as a `dynamodb-onetable` model. Try to `Import model`. It does nothing.

**Comment by RafalWilinski** [comment]
You cannot import dynamodb-onetable models, only NoSQL workbench models.

**Comment by ebisbe** [comment]
How do you save the model and work with it later if you use the ${} feature? I ended up using NoSQL workbencth
