### ISSUE TITLE
Bug when create a table with Global Index

### ISSUE THREAD

**Issue by alambertt** [Dynobase/dynobase#17]
I don't know whats this means. I want to create a table with a index with just one key primary partition. I guess the error was by the empty field in the Global Index form

![image](https://user-images.githubusercontent.com/6148597/133305615-08a1d3ee-2117-45c0-a071-526b58d63256.png)

By the way, could you please add the feature for create indexes over the tables once it is created?? Thks

**Comment by RafalWilinski** [comment]
> I guess the error was by the empty field in the Global Index form

Exactly. You need to specify the sortKey of `EventsById` index. I think we can improve validation on our end a bit more. 

The second request: We got that on our radar!

**Comment by alambertt** [comment]
Yep, I think is not necessary to specify the Sort Key in an Index or in a table
