### ISSUE TITLE
some weird behavious with shift key when trying to edit query conditions

### ISSUE THREAD

**Issue by danbdo** [Dynobase/dynobase#188]
I am on Windows 11 here.

I  have a table loaded with items... browse through data. Then I want to update the query above the table... want to use the Shift key to type upper case letters there. So I click the filter field and start typing. 
What happens then is:
- lower case letters are fine
- when I need to enter upper case letters Dynobase would instead start to overwrite the attribute of the item I happend to select last in the results pane

This does not happen if I don't select an item first after running a scan/query.

**Comment by RafalWilinski** [comment]
I believe this issue is now solved in 1.9.2 https://github.com/Dynobase/dynobase/releases/tag/1.9.2
