### ISSUE TITLE
Single-Table Designer Access Patterns escape the sidebar

### ISSUE THREAD

**Issue by misterjoshua** [Dynobase/dynobase#189]
Version: Dynobase v1.9.1
OS: Windows 10 21H2

When I save queries with moderate length names, their names and trash can icons escape the Access Patterns sidebar and overlap with the query results:

![image](https://user-images.githubusercontent.com/644092/161638594-ded8452c-e0f4-4fb6-9ecb-a04bc87ea5c9.png)

In this situation, I would suggest:

- The access patterns sidebar should have a horizontal scroll or the overflow should be hidden/clipped; and
- I should be able to resize the sidebar to fit the long names.

**Comment by RafalWilinski** [comment]
Fixed in 10.0.4
