### ISSUE TITLE
Option Clicking a table item no longer opens the the editor pane

### ISSUE THREAD

**Issue by rizowski** [Dynobase/dynobase#192]
# Steps to reproduce
  1. Open a table
  2. Option + Click a table row
  3. Notice the editor window does not appear

## System Details
Dynobase Version: 1.9.1
OS: MacOS Monterey 12.3.1

**Comment by gparonitti** [comment]
Same here! And  #191 too 😅.

**Comment by RafalWilinski** [comment]
Fixed in 1.10.0
