### ISSUE TITLE
Dynobase 1.9.2 is not loading profiles on M1

### ISSUE THREAD

**Issue by bart** [Dynobase/dynobase#193]
Looks like Dynobase 1.9.2 does not load profiles anymore. Sticking on "Loading profiles" circle after starting the app. Unfortunately I currently have the feeling that with every new "feature" more bugs are coming into the app. That's not good. Have to downgrade to a previous version to be able to use it but I think that's not intended by an update, right?

**Comment by RafalWilinski** [comment]
Sorry for the inconvenience. Are you able to provide logs from the `~/Library/Logs/Dynobase` directory? If you're not comfortable posting them there, can you please send us to support@dynobase.dev? Thanks

**Comment by RafalWilinski** [comment]
Fixed in https://github.com/Dynobase/dynobase/releases/tag/1.9.3
