### ISSUE TITLE
Inline editing of objects not possible anymore

### ISSUE THREAD

**Issue by bart** [Dynobase/dynobase#194]
After updating from 1.7.x to 1.9.x I realised that inline editing objects (or array of objects) isn't possible anymore. It worked before without any problem by double click -> change. But now it just displays [object Object] and I'm not able to edit it inline anymore. Why did you remove this helpful future? Please add it back, thanks!

**Comment by bart** [comment]
+1

**Comment by RafalWilinski** [comment]
Re-added in 10.0.2
