### ISSUE TITLE
Empty object for index "__id" breaks the onetable model

### ISSUE THREAD

**Issue by dj-rabel** [Dynobase/dynobase#196]
We saw something about this "__id" thing in the changelog but we're using the newest version 1.9.3 and in our onetable export this index "__id" appears as an empty object, which breaks the import into our TypeScript code.

Screentshot right from a fresh onetable export with 1.9.3
![image](https://user-images.githubusercontent.com/4653214/164520274-72e40708-ab1c-411a-8d20-18b04b8d53b6.png)

Onetable requires every property of a model to have at least the "type" set.

Removing the line >"__id": {},< temporarily fixes it. But obviously only until the next export.

**Comment by RafalWilinski** [comment]
Fixed in 1.10.2
