### ISSUE TITLE
Query generates invalid ExpressionAttributeNames for keys with - character

### ISSUE THREAD

**Issue by martin-macak** [Dynobase/dynobase#197]
When queries table contains key that contains `-` or any other special character then Dynobase generates invalid `ExpressionAttributeNames`.

Example: When there is `GI-2-PK` then Dynobase generates `#DDB_GI-2PK` which is invalid. This makes Dynobase unusable for tables that have indexes or attributes that contain those characters.

These attribute names are entirely generated by Dynobase, so it should be easy to replace '-' with '_', which is valid attribute name.

**Comment by RafalWilinski** [comment]
This has been fixed in 2.2.
