### ISSUE TITLE
Open log on failed import not working

### ISSUE THREAD

**Issue by FemkeBuijs** [Dynobase/dynobase#2]
When I am trying to import an exported csv file (without any adjustments), in an empty table, all imports fail. When I am trying to open the log to see why, nothing happens:

<img width="433" alt="Screenshot 2020-03-24 at 13 12 10" src="https://user-images.githubusercontent.com/32512274/77424260-19671580-6dd1-11ea-9fde-d8801ff3c61d.png">

Funny enough, I do get the 'Success' alert, as if the import was successful.

Regarding the failed imports, I suspect it is because some fields have null values. How do I go about this? It is an exact export from the database (using Dynobase), that I can no longer import because of null values.

**Comment by RafalWilinski** [comment]
Hi! Thanks for bug report. Can you please check if latest version (0.4.7) solved that issue? If your trial has expired, please email me (rafal@dynobase.dev). I will extend your trial.

**Comment by FemkeBuijs** [comment]
@RafalWilinski thanks! I am currently working on another project, but later this week I will email you to extend the trial and test the issue if that's ok!
