### ISSUE TITLE
Run a Scan on a GSI in "Simple" mode

### ISSUE THREAD

**Issue by rogerchi** [Dynobase/dynobase#20]
It doesn't seem possible currently to run a scan on a GSI (useful for sparse indexes) in the "Simple" operation builder.  I am able to if I manually add an IndexName parameter to the Query box.

**Comment by RafalWilinski** [comment]
It is possible. Simply type GSI's partition name into the "Field Name" and Dynobase will automatically switch to Query on that index:
![CleanShot 2021-09-17 at 12 55 09](https://user-images.githubusercontent.com/3391616/133771590-0dfb8ef8-b20a-48d6-944c-0b527aef84a5.png)

**Comment by rogerchi** [comment]
But I want to run a Scan (across all possible PKs), and that option looks like it runs a Query (need to define a PK)?

**Comment by rogerchi** [comment]
More details: I specify my gsi's partition name into the "Field Name" and it switches to Query, which asks me to specify an Attribute value for the PK (if I leave it blank the Query fails).  It gives me an option to run a Scan instead, but that appears to run against the main table and not the gsi.  I would like to run the Scan on the GSI which would return all the rows of the GSI.
