### ISSUE TITLE
[Feature request] Improved Copy action on right click.

### ISSUE THREAD

**Issue by slipdexic** [Dynobase/dynobase#202]
When working with data in a table.

Currently  when I click copy , I get the whole ROW in json, which is a good thing, just not in my daily use case.
I can work around this by clicking "Edit this attribute"  and copying the  highlighted (which I have to always do twice before it highlights).

So just a simple option in the Menu "Copy Attribute" that just copies the value of current attribute under the mouse pointer.
Also the same action for CTRL+C which currently does nothing.

**Comment by RafalWilinski** [comment]
Added in 2.2
