### ISSUE TITLE
Window crash when add second attribute name to query

### ISSUE THREAD

**Issue by vavarodrigues** [Dynobase/dynobase#208]
Version 1.10.2

SO macOS Monterey Version 12.4

When I add the second attribute starting with letter `O` 
<img width="1199" alt="Screen Shot 2022-07-12 at 14 44 18" src="https://user-images.githubusercontent.com/5587681/178560519-902197a4-7cfc-4f01-813d-c0f0f7066d13.png">

It happens
<img width="1302" alt="Screen Shot 2022-07-12 at 14 56 24" src="https://user-images.githubusercontent.com/5587681/178560695-28edbc0b-ee2b-466c-b465-1d9b1d23bccd.png">

**Comment by rileypetersen** [comment]
Same here, 1.10.2, Windows 11.

I also tried the following:

1. Enter secondary (non-indexed) filter first
2. Enter primary (indexed) filter second

I was able to enter both of these successfully, but as soon as I ran the query it crashed.

Requires full reset to get out of it.

**Comment by RafalWilinski** [comment]
Fixed in 1.10.4
