### ISSUE TITLE
Unable to export models from Single-Table Designer (version 1.10.8). 

### ISSUE THREAD

**Issue by rheinardkorf** [Dynobase/dynobase#219]
Steps to reproduce:

* Create a new model in the Single-Table Designer.
* Create at least one item.
* Click export arrow to export the model.

Expected result:
* I am able to click on one of the export options available.
* I am able to select the destination for the file.

Actual results:
* I am presented with export options.
* I am unable to select one of the options.

Resolution:

I have had to downgrade to version 1.10.5 to be able to export.

cc @RafalWilinski

**Comment by lordplagus02** [comment]
+1

**Comment by RafalWilinski** [comment]
Yep, I've realised I have broken all exports functionality across the app 😞  Sorry, fixing it shortly!

**Comment by ebisbe** [comment]
> Yep, I've realised I have broken all exports functionality across the app 😞 Sorry, fixing it shortly!

This is also fro the Export `Selection` and `Current results` right? I was going to fill an issue.

**Comment by lordplagus02** [comment]
Any news on this? We'd like to trial this properly

**Comment by RafalWilinski** [comment]
This has been fixed in 2.0
