### ISSUE TITLE
Cannot add new profiles

### ISSUE THREAD

**Issue by abury** [Dynobase/dynobase#220]
I'm using SSO and it's working fine for one of the profiles, however whenever I try and add any other profile it just doesn't work. There isn't any error message that I can see.

Clicking '+ Add new Profile' brings me to the settings page, and the profile I want to add is showing in 'Included AWS Profiles', but it's not appearing in the dropdown list.

I've tried removing and re-adding it, I'm at a bit of a loss as to what to do now.

**Comment by RafalWilinski** [comment]
Hi Aron, sorry for the inconvenience. Have you tried clicking "Reload profiles" after changing included profiles? After that, a new profile (assuming it's valid) will appear in the dropdown.

**Comment by abury** [comment]
Hi @RafalWilinski, I did but nothing ever happened. I've removed the app and re-installed and the issue seems to be resolved.
