### ISSUE TITLE
unable to switch to added profile

### ISSUE THREAD

**Issue by corleymj** [Dynobase/dynobase#221]
<img width="614" alt="Screen Shot 2022-09-02 at 3 03 43 PM" src="https://user-images.githubusercontent.com/4743542/188228130-2d7880eb-9f9e-4f56-8712-98402c21cf4a.png">

I've added a profile here "bprod" that I am unable to select from the dropdown.  Have tried removing/readding + restarting dynobase and no luck.

**Comment by RafalWilinski** [comment]
Have you tried clicking "Reload profiles" afterward? It's below the list of profiles.
