### ISSUE TITLE
2.2.0 Update breaks File Import (M1 Mac)

### ISSUE THREAD

**Issue by jamesatfish** [Dynobase/dynobase#232]
Attempting to import to a table using the File Import function on v2.2.0 on an M1 Mac no longer works.  Clicking the 'File' button has no immediate response from the app, and after 30-60 seconds the entire app screen turns white.  Restarting the app is the only way to restore functionality.

Downloading the previous 2.1.1 build from Github restored the File Import function to normal operation.

**Comment by jladdison** [comment]
It is broken on Mac Intel and Windows as well.

**Comment by RafalWilinski** [comment]
Confirmed, deploying a fix right now.

**Comment by RafalWilinski** [comment]
Fixed in 2.2.1: https://github.com/Dynobase/dynobase/releases/tag/v2.2.1
