### ISSUE TITLE
2.2.4 Release Page has 2.2.3 Binaries

### ISSUE THREAD

**Issue by rcoundon** [Dynobase/dynobase#233]
The binaries listed on the release page are for the previous release

**Comment by rcoundon** [comment]
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/9136570/215604883-9e084952-cdd7-4bb7-aad7-c7c3043ca225.png">

**Comment by RafalWilinski** [comment]
Thanks for pointing this out! I'm going to close this one since we have 2.3.0 already
