### ISSUE TITLE
Tooltip explaining how Dynobase automatically does Query instead of Scan when possible

### ISSUE THREAD

**Issue by RafalWilinski** [Dynobase/dynobase#24]
It is a common question I get - how can I query over a GSI? Answer is quite simple - just type GSI's partition key in the attribute field and Dynobase will automatically switch to querying instead of scanning. It should be explained somewhere.

**Comment by rogerchi** [comment]
This is related to my closed issue -- what if you want to run the Scan on the GSI (not a query, I want all rows of the GSI returned), is that currently possible?  My use case is that I have a sparse index GSI that I want to scan/return all records for, I do not want to specify the PK for the GSI for a Query.
