### ISSUE TITLE
Export saved queries into the model's exported definition

### ISSUE THREAD

**Issue by RafalWilinski** [Dynobase/dynobase#51]

**Comment by danbdo** [comment]
If that is the only way to retain the queries between editing sessions: Yes, that's a blocker.
To me, these queries are a main focus point when evolving a model. Essentially I start with those (mentally) before having the first entity type or attribute. And I keep working along those queries while I work on the model to make sure I don't break an access pattern with a change to the model

**Comment by RafalWilinski** [comment]
Added in 1.10.0
