### ISSUE TITLE
The "Check Update" option doesn't work

### ISSUE THREAD

**Issue by alambertt** [Dynobase/dynobase#64]
When I press `Dynobase->Check Updates` option on top menu nothing happens.

**Comment by alambertt** [comment]
> Which OS are you using? Which version you're currently using? If you're on Mac and on version 1.7.0, it won't work because I still haven't published the zipped version of the binary (updater expects that).

I´m using Windows 10 64x and Im using the version 1.7.0 of Dynobase

**Comment by alambertt** [comment]
Hi @RafalWilinski any update about this issue??

**Comment by alambertt** [comment]
https://github.com/Dynobase/dynobase/issues/153#issuecomment-1195348049

**Comment by RafalWilinski** [comment]
Fixed in 2.0
