### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by sorgnardt** [Dynobase/dynobase#8]
when exporting a dataset and reimporting
May fails, with log error

  constructor: 'TypeError',
  stack: "TypeError: Cannot read property 'toString' of null\n" +
    '    at /Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:101:48\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at convertItemTypes (/Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:58:23)\n' +
    '    at Importer.<anonymous> (/Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:370:46)\n' +
    '    at step (/Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:43:23)\n' +
    '    at Object.next (/Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:24:53)\n' +
    '    at /Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:18:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:14:12)\n' +
    '    at writeItem (/Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:338:54)\n' +
    '    at Stream.<anonymous> (/Applications/Dynobase.app/Contents/Resources/app.asar/build/ipc/Importer.js:318:25)\n' +
    '    at Stream.emit (events.js:210:5)\n' +
    '    at Stream.EventEmitter.emit (domain.js:476:20)\n' +
    '    at drain (/Applications/Dynobase.app/Contents/Resources/app.asar/node_modules/through/index.js:36:16)\n' +
    '    at Stream.stream.queue.stream.push (/Applications/Dynobase.app/Contents/Resources/app.asar/node_modules/through/index.js:45:5)\n' +
    '    at Parser.parser.onValue (/Applications/Dynobase.app/Contents/Resources/app.asar/node_modules/JSONStream/index.js:118:16)'
}

**Comment by phil-andrews** [comment]
I'm having the same issue. The problem is something I don't believe a user can resolve. It seems that on import, whatever happens behind the scenes resolves field values that are blank or falsey to null. So zero, `false`, and `undefined` all resolve to `null`.
