### ISSUE TITLE
AppImage not working in Ubuntu 20.04

### ISSUE THREAD

**Issue by simonedesogus** [Dynobase/dynobase#9]
When trying to run the Dynobase AppImage, I get undefined:0 illegal access.
I tried 1.3.3 and 1.3.2 and I get the same error with or without sudo.

**Comment by simonedesogus** [comment]
I solved this by installing the snap 1.3.4. The problem is probably generated by running the appImage/dynobase via ssh, instead of using a Desktop Environment, since I don't get this error when using X2Go

**Comment by WilliamCadenas21** [comment]
I'm trying to install the 1.3.4 AppImage and doesn't work and also the .snap on Ubuntu 20.04, what am I doing wrong ? 

amd64.snap:
![image](https://user-images.githubusercontent.com/20405614/111885719-89ce5580-8997-11eb-872d-674675db8640.png)

AppImage:
![image](https://user-images.githubusercontent.com/20405614/111885753-c306c580-8997-11eb-946b-b2f881b1d309.png)

**Comment by WilliamCadenas21** [comment]
> I solved this by installing the snap 1.3.4. The problem is probably generated by running the appImage/dynobase via ssh, instead of using a Desktop Environment, since I don't get this error when using X2Go

what does it mean, can you show me how I have to do ?

**Comment by simonedesogus** [comment]
Hello William.

Open the terminal, give execution rights to the file and just try to run
the file by doing ./Dynobase1.3.4.AppImage (check that the filename is
correct)
This didn't work for me.
What worked was installing snap (Google how to) and then always from the
terminal, do a sudo snap install Dynobase.1.3.4.snap

If you are still stuck I'll try to give more information on Monday

Cheers,
Simone

**Comment by WilliamCadenas21** [comment]
> Hello William. Open the terminal, give execution rights to the file and just try to run the file by doing ./Dynobase1.3.4.AppImage (check that the filename is correct) This didn't work for me. What worked was installing snap (Google how to) and then always from the terminal, do a sudo snap install Dynobase.1.3.4.snap If you are still stuck I'll try to give more information on Monday Cheers, Simone

The first one work for me, thank you so much !!
